comilper:comilper_server.cpp
	g++ comilper_server.cpp -o comilper -ljsoncpp -pthread

.PHONY:clean
clean:
	rm -rf comilper

.PHONY:cleanLS
cleanLS:
	rm -rf ./temp/*.exe ./temp/*.stderr ./temp/*.stdin ./temp/*.stdout ./temp/*.comilp_error